.\" dudders.8 -*- nroff -*-
.\" Copyright 2007--2010 Dean Scarff
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License"); you
.\" may not use this file except in compliance with the License.  You
.\" may obtain a copy of the License at
.\"
.\"     http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.Dd Nov 29, 2020
.Dt DUDDERS 8
.Sh NAME
.Nm dudders
.Nd update DNS record
.Sh SYNOPSIS
.Nm dudders
.Op Fl T
.Op Fl k Ar PRIVKEY
.Op Fl n Ar KEYNAME
.Op Fl m Ar MNAME
.Op Fl z Ar ZONE
.Ar DOMAIN
.Ar TTL
.Ar ADDRESS
.Sh DESCRIPTION
Perform a DNS update request to set 
.Ar DOMAIN Ap s
A record to
.Ar ADDRESS ,
with
.Ar TTL
seconds to live, overwriting any previous A records for the domain in
the Internet class.
An RSA private key is loaded from standard input, or from the file
.Ar PRIVKEY .
The update is sent to the zone's master server, and authenticated
with SIG(0) using the private key's signature.
.Pp
If the filename
.Ar PRIVKEY
is provided and the filename is in
.Xr dnssec-keygen Ap s
format, the keyname can be inferred from the
filename.
Otherwise, the keyname must be provided via the
.Ar KEYNAME
option.
.Pp
The
.Ar MNAME
and
.Ar ZONE
options can be used to override the authority for testing purposes.
If either of these options are not specified, the leading labels are
stripped away from
.Ar DOMAIN
until an SOA record is found, and the missing values are filled from
the SOA response.
.Pp
The private key must be in the format generated by
.Xr dnssec-keygen
using the
.Ql \-a RSAMD5
option.
The reference key format uses colon-separated key value pairs and
base64-encoded unsigned multiprecision integer key components.
.Sh DIAGNOSTICS
The
.Nm
utility exits with 0 iff the server reports that the update was
successful.
.Pp
A DNS Server Failure error may indicate that
.Ar PRIVKEY
is not authorised for signing transactions for
.Ar DOMAIN ,
or that the master server does not support the update protocol.
.Sh OPTIONS
.Bl -tag -width 8n
.It Fl T
Send update message over TCP (default is UDP).
.It Fl k Ar PRIVKEY
Look in the file
.Ar PRIVKEY
for the private key.
.It Fl n Ar KEYNAME
Use the fully qualified domain name
.Ar KEYNAME
to identify the key.
.It Fl m Ar MNAME
Assume the (authoritative) master server is the domain name
.Ar MNAME .
.It Fl z Ar ZONE
Assume that the fully qualified domain name
.Ar ZONE
is authoritative for
.Ar DOMAIN .
.It Fl \-help
Output a brief help message and exit.
.It Fl \-version
Output version information and exit.
.El
.Sh LIMITATIONS
Wildcards are not supported for
.Ar DOMAIN .
.Pp
Only RSA/MD5 keys/signatures are supported.
.Pp
Only A records within the Internet class are supported.
.Sh SEE ALSO
.Xr nsupdate 8
.Xr dnssec\-keygen 8
.Pp
Relevant protocols are defined by the Internet standards RFC1035,
RFC2535, RFC2537 and RFC2931.
.Sh AUTHOR
.Nm
and its manual page were
written by
.An Dean Scarff.
.Sh REPORTING BUGS
Report bugs via the project website:
.Lk https://github.com/p00ya/dudders
