# test.yml -- GitHub Actions tests
# Copyright Dean Scarff
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

name: dudders
on:
  push:
  schedule:
    # Weekly on Thursdays at 08:34.
    - cron: '34 8 * * 4'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: sudo apt-get install clang-format 
    - name: Lint
      run: |
        find . -name '*.[h,c]' -exec clang-format -n '{}' '+' 
  test:
    runs-on: ubuntu-20.04 
    strategy:
      matrix:
        crypto: [ 'openssl', 'gcrypt', 'dl' ]
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: sudo apt-get install autoconf automake libgcrypt20-dev libssl-dev 
    - name: Build and test
      run: |
        autoreconf -i
        ./configure --with-crypto=${{ matrix.crypto }}
        make check
